# Generated by Django 3.2.14 on 2022-11-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20221103_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
